#!/bin/bash
./tools/cleanup
git branch rebase_master
git checkout rebase_master

./tools/rand m_c1 m_c2 m_c3 m_c4 m_c5 
./tools/rand b1_c1 b1_c2 b1_c3 b1_c4 


git add m_c1 ;  git commit -m m_c1

git add m_c2;  git commit -m m_c2

git add m_c3;  git commit -m m_c3

git branch rebase_b1 rebase_master^~1
git checkout rebase_b1

git add b1_c1 ;  git commit -m b1_c1
git add b1_c2 ;  git commit -m b1_c2
git add b1_c3 ;  git commit -m b1_c3
git add b1_c4 ;  git commit -m b1_c4


git checkout rebase_master
git add m_c4;  git commit -m m_c4
git add m_c5;  git commit -m m_c5
git checkout rebase_b1

read -p "[1] create tmp brnach"
git checkout -b tmp_branch

read -p "[2] tmp branch created, before rebase"
git rebase rebase_master

read -p "[3] after rebase"

git branch -f rebase_b1
git checkout rebase_b1
git branch -d tmp_branch
