#!/bin/bash
./tools/cleanup
git branch ex1_master
git checkout ex1_master
#sleep 1
./tools/rand m_c1 m_c2 m_c3 m_c4 m_c5 b1_c1 b1_c2 b1_c3 b1_c4 b2_c1 b2_c2 b2_c3
cp data/check_bad check

git add check ; git add m_c1 ;  git commit -m m_c1
cp data/check_ok check
git add m_c2 check;  git commit -m m_c2
git tag and_here
cp data/check_bad check

git add m_c3 check;  git commit -m m_c3

git branch ex1_b1 ex1_master^~1
#sleep 1

git checkout ex1_b1
#sleep 1
git add b1_c1 ;  git commit -m b1_c1
git add b1_c2 ;  git commit -m b1_c2

git branch ex1_b2
#sleep 1

git checkout ex1_b2
#sleep 1
git add b2_c1 ; git commit -m b2_c1
cp data/check_ok check
git add b2_c2 ; git add check
git commit -m b2_c2
git tag get_here
cp data/check_bad check
git add b2_c3 check; git commit -m b2_c3
git checkout ex1_b1

#sleep 1
git add b1_c3;  git commit -m b1_c3
#sleep 1
git merge --no-edit -m "merge b1 and b2" ex1_b2
git add b1_c4 ;  git commit -m b1_c4
git checkout ex1_master
git add m_c4 ;  git commit -m m_c4
git merge --no-edit -m "merge master and b1" ex1_b1
git add m_c5 ;  git commit -m m_c5

